### PR TITLE
- enable optional cookie container to be injected into the constructo…

### PR DESCRIPTION
**Pull request by itb2k13**
…r to be used instead of the default private instance

### CODE REVIEW

**Comment by itb2k13** [comment]
I'd like the ability to be able to inject a CookieContainer that contains other cookies to be sent with the HttpRequests (such as SessionIDs).

**Comment by createS0ftware** [comment]
This is needed

**Comment by kade-robertson** [comment]
You can already set custom cookie containers -- https://github.com/elcattivo/CloudFlareUtilities/issues/14#issuecomment-289019573.

**Comment by elcattivo** [comment]
Thanks for your work @itb2k13 , but as kade said, using a custom cookie container is already possible. I don't think this change would provide any benefit.

**Pull request closed without merging**
